import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/component/Sidbar/theme-provider";
import HeadeSidebar from "@/component/Sidbar/headeSidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/component/Sidbar/appSidebar";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/component/Sidbar/ModeToggle";
import PageHeading from "@/component/Sidbar/pageheading";
import { LuPanelLeft } from "react-icons/lu";
import { CustomSidebarButton } from "@/component/Sidbar/CustomSidebarButton";

// const geistSans = Poppins({
//   variable: "--font-geist-sans",
//    weight: ["400", "500", "600", "700"], 
//   subsets: ["latin"],
// });

// const geistMono = Poppins({
//   variable: "--font-geist-mono",
//    weight: ["400", "500", "600", "700"], 
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose as per need
  variable: "--font-poppins", // optional, for CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <HeadeSidebar  /> */}
          <SidebarProvider className="group/sidebar">
            <AppSidebar />
            <SidebarInset>
              <header className="flex justify-between border-b bg-[#2F53E6] border-black h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
               
                <CustomSidebarButton />
                
                <div className="flex items-center gap-2 px-4"> 
                  <PageHeading />
                  <Separator
                    orientation="vertical"
                    className=" data-[orientation=vertical]:h-6"
                  />
                  <ModeToggle />
                </div>


              </header>
              <div className="homerr flex flex-1 flex-col gap-4">

                {children}

              </div>
            </SidebarInset>

          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
